# Generated by Django 5.2.17 on 2026-09-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interviewer", "Interviewer"),
                    ("developer", "Developer"),
                    ("virtual_assistant", "Virtual assistant"),
                ],
                help_text="What the member does on the team. The admin picks it when approving them.",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
