# Generated by Django 5.2.17 on 2026-09-29 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_default_interview_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={
                "ordering": ["-date", "-start_time"],
                "verbose_name": "work entry",
                "verbose_name_plural": "work entries",
            },
        ),
        migrations.AddField(
            model_name="interview",
            name="bids",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Bids sent that day. Only for bid entries; empty for interviews.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="total_bids",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="interview",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="interview",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interview_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interviews",
                to="tracker.interviewtype",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interview_with",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="interview",
            name="role",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="interview",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payout",
            name="interview_count",
            field=models.PositiveIntegerField(
                help_text="Interviews in this payment (not developer work or bids)."
            ),
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bids__isnull", True),
                        ("end_time__isnull", False),
                        ("start_time__isnull", False),
                    ),
                    models.Q(
                        ("bids__isnull", False),
                        ("end_time__isnull", True),
                        ("interview_type__isnull", True),
                        ("start_time__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="entry_is_timed_or_bids",
                violation_error_message="An entry has either start and end times, or a number of bids.",
            ),
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bids__isnull", False)),
                fields=("user", "date"),
                name="one_bid_entry_per_member_per_day",
                violation_error_message="Bids for this day are already logged.",
            ),
        ),
    ]
